### ISSUE TITLE
the content of package.json was incorrect 

### ISSUE THREAD

**Issue by happyguohua** [crysislinux/chrome-react-perf#1]
the package.json should be updated to:

`{
  "name": "chrome-react-perf",
  "version": "0.0.0",
  "description": "An Operation Interface for react-addons-perf Package",
  "scripts": {
    "dev": "node scripts/dev",
    "build": "NODE_ENV=production node scripts/build",
    "test": "jasmine"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/crysislinux/chrome-react-perf.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/crysislinux/chrome-react-perf/issues"
  }
}`

**Comment by crysislinux** [comment]
Thanks for pointing that out, fixed in e7f9831b1836a1cf9aab8f33f9c398fb8143f05b
