### ISSUE TITLE
Give hint about expose-loader

### ISSUE THREAD

**Issue by aymericbouzy** [crysislinux/chrome-react-perf#10]
`expose-loader` was not part of my dev dependencies and I wasted a lot of time finding about it on the internet. Adding a comment about it in the documentation would have helped me a lot getting started.

**Comment by crysislinux** [comment]
I am sorry about that. 

https://github.com/crysislinux/chrome-react-perf#expose-perf

this section tells something about the expose-loader. And there is a way to avoid using it.

It's true that someone may miss that part if he/she is not familiar with webpack.

I am considering to add more details about the loader when I have time to publish next version.

Thanks.
