### ISSUE TITLE
Only import it in dev mode

### ISSUE THREAD

**Issue by tcoopman** [crysislinux/chrome-react-perf#6]
What would your strategy be to only include this in development builds?

Something like doesn't work because `import` only works on toplevel.

``` js
if (NODE_ENV !== 'production') {
    import 'expose?Perf!react-addons-perf';
}
```

**Comment by crysislinux** [comment]
Do you mind using require instead?

``` js
if (NODE_ENV !== 'production') {
   require('expose?Perf!react-addons-perf');
}
```

**Comment by tcoopman** [comment]
@crysislinux Yeah, I know that works, I was mostly wondering if there is an alternative

**Comment by jfsiii** [comment]
@tcoopman `import` favors static analysis over flexibility and doesn't support dynamic imports. 

IIUC, you should use `System.import` for this. See [`systemjs`](https://github.com/systemjs/systemjs) and [`es6-module-loader`](https://github.com/ModuleLoader/es6-module-loader) for more info, but I believe you could do something like:

``` javascript
if (NODE_ENV !== 'production') {
  System.import('react-addons-perf').then(Perf => window.Perf = Perf)
}
```

**Comment by tcoopman** [comment]
@jfsiii thanks!
