### ISSUE TITLE
Not working on Chrome dev channel (Version 51.0.2704.4 dev (64-bit)

### ISSUE THREAD

**Issue by CodyReichert** [crysislinux/chrome-react-perf#8]

**Comment by larvata** [comment]
Please restart Chrome and try again. I have the same issue and after I restart the Chrome the problem has gone.

**Comment by crysislinux** [comment]
or try in a incognito window. 

Did the Perf appear on the dev tools pane?

**Comment by CodyReichert** [comment]
Wow I didn't realize I actually submitted this issue. I thought I closed the tab.

There are no issues in Chrome dev channel, I simply didn't read the README fully. Works great - sorry for the noise!
